"""add processed_items table

Revision ID: 18ff3d1326cf
Revises: 704d5189b4d6
Create Date: 2026-08-18 13:25:07.386254

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18ff3d1326cf"
down_revision = "704d5189b4d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_items",
        sa.Column("guid", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("guid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_items")
    # ### end Alembic commands ###
